### ISSUE TITLE
infografia 

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-christopheremv#1]
[infografia contratos inteligentes.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-christopheremv/files/8566491/infografia.contratos.inteligentes.pdf)

**Comment by Sandra631** [comment]
18% bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado
